server:
  port: 8866

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.242.110.11:3306/ict
      username: root
      password: 1121135791121Ab

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ict.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      ftt:
        mapper: debug
        service: info
        controller: info

ict:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 72000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    access-key-id: ${ict.alioss.access-key-id}
    access-key-secret: ${ict.alioss.access-key-secret}
    endpoint: ${ict.alioss.endpoint}
    bucket-name:  ${ict.alioss.bucket-name}

pagehelper:
  helper-dialect=mysql
  reasonable=true
